apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless-redis
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: paperless-redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: paperless-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: paperless-redis
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  selector:
    app.kubernetes.io/name: paperless-redis
  ports:
    - port: 6379
      targetPort: 6379
