{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Home Assistant
    gethomepage.dev/group: Daily
    gethomepage.dev/icon: home-assistant.png
    gethomepage.dev/description: Home automation
    gethomepage.dev/weight: "5"
    gethomepage.dev/external: "true"
    gethomepage.dev/siteMonitor: http://{{ .Values.upstream.address }}:{{ .Values.upstream.port }}
    gethomepage.dev/widget.type: homeassistant
    gethomepage.dev/widget.url: http://{{ .Values.upstream.address }}:{{ .Values.upstream.port }}
    gethomepage.dev/widget.key: {{ "{{HOMEPAGE_VAR_HOMEASSISTANT_KEY}}" | quote }}
    gethomepage.dev/widget.fields: '["people_home", "lights_on", "switches_on"]'
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: {{ .Values.upstream.port }}
{{- end }}
