{{- with .Values.homepageSecrets }}
{{- if .enabled }}
{{- $ctx := . }}
{{- range .apps }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ .name }}
  namespace: {{ $ctx.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  vaultAuthRef: {{ $ctx.vaultAuthRef }}
  type: kv-v2
  mount: {{ $ctx.mount | quote }}
  path: {{ .path | quote }}
  refreshAfter: {{ $ctx.refreshAfter | quote }}
  destination:
    name: {{ .name }}
    create: true
    transformation:
      excludeRaw: true
      templates:
        {{- range $env, $key := .env }}
        {{ $env }}:
          text: '{{ printf "{{ .Secrets.%s }}" $key }}'
        {{- end }}
{{- end }}
{{- end }}
{{- end }}
