upstream:
  address: 192.168.0.250
  port: 8123

ingress:
  enabled: true
  className: traefik
  host: home.gruzin.eu
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  tls:
    enabled: true
    secretName: home-assistant-tls

homepageSecrets:
  enabled: true
  namespace: homepage
  vaultAuthRef: homepage
  mount: secret
  refreshAfter: 1h
  apps:
    - name: homepage-home-assistant
      path: home-assistant/homepage
      env:
        HOMEPAGE_VAR_HOMEASSISTANT_KEY: token
