apiVersion: v2
name: homepage
description: gethomepage dashboard, populated from gethomepage.dev/* ingress annotations
type: application
version: 0.1.0
appVersion: "1.13.2"

maintainers:
  - name: Grzegorz Jagielski
    url: https://github.com/ModerNews
