apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-library
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/hdd/media/photos
  storageClassName: ""
  claimRef:
    name: immich-library
    namespace: immich
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""
  volumeName: immich-library
