{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "speedtest-tracker.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
    {{- if .Values.homepage.enabled }}
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: {{ .Values.homepage.name | quote }}
    gethomepage.dev/group: {{ .Values.homepage.group | quote }}
    gethomepage.dev/icon: {{ .Values.homepage.icon | quote }}
    gethomepage.dev/description: {{ .Values.homepage.description | quote }}
    gethomepage.dev/weight: {{ .Values.homepage.weight | quote }}
    gethomepage.dev/pod-selector: "app.kubernetes.io/instance={{ .Release.Name }}"
    gethomepage.dev/widget.type: speedtest
    gethomepage.dev/widget.url: "http://{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local"
    gethomepage.dev/widget.version: "1"
    gethomepage.dev/widget.bitratePrecision: "1"
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: 80
{{- end }}
