apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Sonarr
    gethomepage.dev/group: Media management
    gethomepage.dev/icon: sonarr.png
    gethomepage.dev/description: TV series
    gethomepage.dev/pod-selector: io.kompose.service=sonarr
    gethomepage.dev/weight: "30"
    gethomepage.dev/widget.type: sonarr
    gethomepage.dev/widget.url: http://sonarr.arr-stack.svc.cluster.local:8989
    gethomepage.dev/widget.key: {{ "{{HOMEPAGE_VAR_SONARR_KEY}}" | quote }}
    gethomepage.dev/widget.enableQueue: "true"
    gethomepage.dev/widget.fields: '["wanted", "queued", "series"]'
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.image-pull-policy: Always
    kompose.service.expose: sonarr.bay.gruzin.eu
    kompose.service.expose.ingress-class-name: traefik
    kompose.service.expose.tls-secret: sonarr-tls
    kompose.version: 1.38.0 (HEAD)
    kompose.volume.type: hostPath
    kuma.sonarr.http.accepted_statuscodes: '["200-299"]'
    kuma.sonarr.http.name: Sonarr TV
    kuma.sonarr.http.url: https://sonarr.bay.gruzin.eu
  labels:
    io.kompose.service: sonarr
  name: sonarr
spec:
  ingressClassName: traefik
  rules:
    - host: sonarr.bay.gruzin.eu
      http:
        paths:
          - backend:
              service:
                name: sonarr
                port:
                  number: 8989
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - sonarr.bay.gruzin.eu
      secretName: sonarr-tls
