{{- with .Values.vault }}
{{- if .enabled }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: {{ $.Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  address: {{ .address | quote }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: {{ $.Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  vaultConnectionRef: {{ $.Release.Name }}
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: {{ .role | quote }}
    serviceAccount: {{ .serviceAccount | quote }}
{{- $vault := . }}
{{- range .ownSecrets }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ .name }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  vaultAuthRef: {{ $.Release.Name }}
  type: kv-v2
  mount: {{ $vault.mount | quote }}
  path: {{ .path | quote }}
  refreshAfter: {{ $vault.refreshAfter | quote }}
  destination:
    name: {{ .name }}
    create: true
    transformation:
      excludeRaw: true
      templates:
        {{- range $env, $key := .env }}
        {{ $env }}:
          text: '{{ printf "{{ .Secrets.%s }}" $key }}'
        {{- end }}
{{- end }}
{{- end }}
{{- end }}
