apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: memos
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/usememos/helm.git
      targetRevision: HEAD
      path: .
      helm:
        releaseName: memos
        valueFiles:
          - $values/memos/values.yaml
    - repoURL: https://github.com/ModerNews/homelab-helm.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: memos
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
